### ISSUE TITLE
Simplified model loading

### ISSUE THREAD

**Issue by rgeirhos** [RayDeeA/ibinn_imagenet#1]
Hey @RayDeeA,

Thanks for making this available, very cool work!

I was wondering whether it would be possible to make the pre-trained model available via a simple load function?
E.g. such that if one would like to test the model on some images, one could import it like this:
```python
from ibinn import load_model
trustworthy_model = load_model(pretrained=True)
```

Kind regards,
Robert

**Comment by RayDeeA** [comment]
Hi Robert,

Great idea. I will look into it tomorrow and will let you know asap.

Thank you.

**Comment by rgeirhos** [comment]
Awesome, thanks!

**Comment by RayDeeA** [comment]
Hi Robert,

this will work now.

```python
from ibinn_imagenet.model.classifiers.invertible_imagenet_classifier import trustworthy_gc_beta_0, trustworthy_gc_beta_32
beta_0_model = trustworthy_gc_beta_0(pretrained=True)
beta_32_model = trustworthy_gc_beta_32(pretrained=True)
```

In case you have the models already downloaded consider using:

```python
from ibinn_imagenet.model.classifiers.invertible_imagenet_classifier import trustworthy_gc_beta_0, trustworthy_gc_beta_32
beta_0_model = trustworthy_gc_beta_0(pretrained=True, pretrained_model_path="/path/to/beta_0.avg.pt")
beta_32_model = trustworthy_gc_beta_32(pretrained=True, pretrained_model_path="/path/to/beta_32.avg.pt")
```

**Comment by RayDeeA** [comment]
Hi, I squash merged a few commits into one. Please use commit 16e3d57 (also the current head) and ignore the previous notifications within this issue. Tried to delete them but failed.

**Comment by rgeirhos** [comment]
Thank you very much @RayDeeA for your work, makes model loading a breeze!

**Comment by rgeirhos** [comment]
Sorry to re-open this, I believe there's a small issue with the model names.

In file ``invertible_imagenet_classifier.py``, the following line throws an error when loading the model:

```python
data = load_state_dict_from_url(model_urls[beta_str], progress=progress)
```
The error message is:
`IsADirectoryError: [Errno 21] Is a directory: '/root/.cache/torch/checkpoints/'`

I did some debugging and the following works fine:

```python
data = load_state_dict_from_url('https://s3.amazonaws.com/pytorch/models/resnet18-5c106cde.pth')
```
I believe this is due to the fact that `torch.hub.load_state_dict_from_url` requires model names to follow the following pattern: `model-<sha256>.pth`. Therefore, the files for downloading might need to be re-named accordingly.

**Comment by ardizzone** [comment]
> I believe this is due to the fact that torch.hub.load_state_dict_from_url requires model names to follow the following pattern: model-<sha256>.pth. Therefore, the files for downloading might need to be re-named accordingly.

This was not the issue (it only applies if the `check_hash` argument is True).
Instead, the URLs were being parsed incorrectly, because the file was only contained in the query (as in `?p=%2{filename}&`), and not linked to directly (as in the aws example above).

I made a pull request that should hopefully fix it! (https://github.com/RayDeeA/ibinn_imagenet/pull/2)

**Comment by rgeirhos** [comment]
Thanks @ardizzone for this very fast reply!
I can confirm that I'm now able to load the model and run inference. Very nice!
